{
  "openapi": "3.0.0",
  "info": {
    "title": "Fund raise",
    "version": "1.0",
    "description": "Raising funds for a given event"
  },
  "servers": [
    {
      "url": "http://localhost:3000"
    }
  ],
  "paths": {
    "/fund-raisers/{fundraiserReference}/collection": {
      "get": {
        "summary": "/fund-raisers/{fundraiserReference}/collection",
        "tags": [
          "fundraiser"
        ],
        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "example": {
                    "value": {
                      "id": 15,
                      "fundraiserId": 15,
                      "collectionFrom": 23,
                      "amountCollected": 2000,
                      "status": "pledge",
                      "description": "details of the reason for collection",
                      "dateCreated": 2014211124
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "get-fund-raiser-collection",
        "description": "Funds collected for fund raisers",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "fundraiserId": {
                    "type": "integer"
                  }
                }
              }
            }
          },
          "description": ""
        }
      },
      "put": {
        "summary": "/fund-raisers/{fundraiserReference}/collection",
        "tags": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "example": {
                    "value": {
                      "id": 15,
                      "fundraiserId": 15,
                      "collectionFrom": 23,
                      "amountCollected": 3000,
                      "status": "pledge",
                      "description": "details of the reason for collection",
                      "dateCreated": 2014211124
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "put-fund-raiser-collection",
        "description": "Update collection data",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "fundraiserId": {
                    "type": "integer"
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "summary": "/fund-raisers/{fundraiserReference}/collection",
        "tags": [],
        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "example": {
                    "value": {
                      "id": 15,
                      "fundraiserId": 15,
                      "collectionFrom": 23,
                      "amountCollected": 2000,
                      "status": "pledge",
                      "description": "details of the reason for collection",
                      "dateCreated": 2014211124
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "post-fund-raiser-collection",
        "description": "Adding contriution to a fundraise",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "amountCollected": {
                    "type": "number"
                  },
                  "status": {
                    "type": "string"
                  },
                  "description": {
                    "type": "string"
                  }
                }
              }
            }
          }
        }
      },
      "parameters": [
        {
          "schema": {
            "type": "string"
          },
          "name": "fundraiserReference",
          "in": "path",
          "required": true
        }
      ]
    },
    "/fund-raisers": {
      "get": {
        "summary": "/fund-raisers/{fundraiserReference}",
        "tags": [
          "fundraiser"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "example": {
                    "value": {
                      "id": 13,
                      "title": "Contribution towards fee",
                      "avatarId": 23,
                      "reference": "REF-2527255879310",
                      "createdBy": 18,
                      "targetAmount": 20000,
                      "collectedAmount": 0,
                      "fundraiserLink": "https://ban-q.com?r=sGsvsF168sdfssdf",
                      "allowPledge": true,
                      "description": "the reason for the fundraise",
                      "status": "open",
                      "dateDue": 1518201524,
                      "dateCreated": 1518201524,
                      "dateUpdated": 1518201524,
                      "avatar": {
                        "id": 23,
                        "url": null,
                        "dateCreated": 1518201524,
                        "dateUpdated": 1518201524
                      }
                    }
                  }
                }
              }
            }
          },
          "": {
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "example": {
                    "value": {
                      "id": 13,
                      "title": "Contribution towards fee",
                      "avatarId": 23,
                      "reference": "REF-2527255879310",
                      "createdBy": 18,
                      "targetAmount": 20000,
                      "collectedAmount": 0,
                      "fundraiserLink": "https://ban-q.com?r=sGsvsF168sdfssdf",
                      "allowPledge": true,
                      "description": "the reason for the fundraise",
                      "status": "open",
                      "dateDue": 1518201524,
                      "dateCreated": 1518201524,
                      "dateUpdated": 1518201524,
                      "avatar": {
                        "id": 23,
                        "url": null,
                        "dateCreated": 1518201524,
                        "dateUpdated": 1518201524
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "get-fund-raiser",
        "description": "Get a specific fund raise",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "fundraiserId": {
                    "type": "integer",
                    "description": "optional"
                  }
                }
              }
            }
          },
          "description": ""
        }
      },
      "post": {
        "summary": "/fund-raisers",
        "tags": [
          "fundraiser"
        ],
        "responses": {
          "201": {
            "description": "Created",
            "headers": {},
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "example": {
                    "value": {
                      "id": 13,
                      "title": "Contribution towards fee",
                      "avatarId": 23,
                      "reference": "REF-2527255879310",
                      "createdBy": 18,
                      "targetAmount": 20000,
                      "collectedAmount": 0,
                      "fundraiserLink": "https://ban-q.com?r=sGsvsF168sdfssdf",
                      "allowPledge": true,
                      "description": "the reason for the fundraise",
                      "status": "open",
                      "dateDue": 1518201524,
                      "dateCreated": 1518201524,
                      "dateUpdated": 1518201524,
                      "avatar": {
                        "id": 23,
                        "url": null,
                        "dateCreated": 1518201524,
                        "dateUpdated": 1518201524
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "post-fund-raisers",
        "description": "Creating a new fund raiser",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "title": {
                    "type": "string"
                  },
                  "targetAmount": {
                    "type": "number"
                  },
                  "allowPledge": {
                    "type": "boolean"
                  },
                  "description": {
                    "type": [
                      "string",
                      "null"
                    ]
                  }
                }
              }
            }
          },
          "description": "Request body data"
        }
      },
      "put": {
        "summary": "/fund-raisers/{fundraiserReference}",
        "tags": [
          "fundraiser"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "example": {
                    "value": {
                      "id": 13,
                      "title": "Contribution towards fee balance",
                      "avatarId": 23,
                      "reference": "REF-2527255879310",
                      "createdBy": 18,
                      "targetAmount": 20000,
                      "collectedAmount": 0,
                      "fundraiserLink": "https://ban-q.com?r=sGsvsF168sdfssdf",
                      "allowPledge": true,
                      "description": "the reason for the fundraise",
                      "status": "open",
                      "dateDue": 1518291524,
                      "dateCreated": 1518292124,
                      "dateUpdated": 1518201524
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "put-fund-raiser",
        "description": "Update fund raiser data",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "title": {
                    "type": "string"
                  },
                  "targetAmount": {
                    "type": "number"
                  },
                  "allowPledge": {
                    "type": "boolean"
                  },
                  "description": {
                    "type": "string"
                  }
                }
              }
            }
          }
        }
      },
      "parameters": []
    }
  },
  "components": {
    "schemas": {
      "fundRaiser": {
        "title": "fundRaiser",
        "type": "object",
        "description": "fund raiser model",
        "x-tags": [
          "fundraiser"
        ],
        "properties": {
          "id": {
            "type": "integer"
          },
          "title": {
            "type": "string",
            "example": "Contribution towards fee",
            "minLength": 1,
            "maxLength": 50,
            "description": "fund raiser title"
          },
          "avatarId": {
            "type": "integer"
          },
          "reference": {
            "type": "string",
            "minLength": 1,
            "maxLength": 50,
            "description": "unique reference number of the fundraise"
          },
          "createdBy": {
            "type": "integer",
            "description": "unique user id of the creator",
            "minimum": 1,
            "maximum": 15
          },
          "targetAmount": {
            "type": "number",
            "minimum": 1,
            "maximum": 15,
            "description": "amount to be collected"
          },
          "collectedAmount": {
            "type": "number",
            "default": 0,
            "minimum": 1,
            "maximum": 15,
            "description": "amount collected so far"
          },
          "fundraiserLink": {
            "type": "string",
            "minLength": 1,
            "maxLength": 300,
            "description": "fundraiser deep link"
          },
          "allowPledge": {
            "type": "boolean"
          },
          "description": {
            "type": "string",
            "minLength": 1,
            "maxLength": 300,
            "description": "the reason for the fundraise"
          },
          "status": {
            "type": "string",
            "default": "open",
            "example": "open/closed"
          },
          "dateDue": {
            "type": "integer"
          },
          "dateCreated": {
            "type": "integer"
          },
          "dateUpdated": {
            "type": "integer"
          }
        },
        "required": [
          "id",
          "title",
          "reference",
          "createdBy",
          "targetAmount",
          "collectedAmount",
          "fundraiserLink",
          "description",
          "status"
        ]
      },
      "fundRaiserCollections": {
        "title": "fundRaiserCollections",
        "type": "object",
        "description": "collection for fund raise",
        "x-tags": [
          "fundraiser"
        ],
        "x-examples": {},
        "properties": {
          "id": {
            "type": "integer",
            "minimum": 1,
            "maximum": 15
          },
          "paymentId": {
            "type": "integer"
          },
          "fundraiserId": {
            "description": "the fund raiser reference number/id",
            "type": "integer"
          },
          "collectionFrom": {
            "type": "integer",
            "description": "unique id of contributor"
          },
          "amountCollected": {
            "type": "number",
            "minimum": 1,
            "maximum": 15
          },
          "status": {
            "type": "string",
            "default": "paid",
            "minLength": 1,
            "maxLength": 10,
            "description": "payment or pledge"
          },
          "description": {
            "type": [
              "string",
              "null"
            ],
            "minLength": 1,
            "maxLength": 300,
            "description": "details of the reason for collection"
          },
          "dateCreated": {
            "type": "integer"
          }
        },
        "required": [
          "id",
          "fundraiserId",
          "collectionFrom",
          "amountCollected",
          "status",
          "dateCreated"
        ]
      }
    },
    "securitySchemes": {
      "API Key - 1": {
        "type": "http",
        "scheme": "Bearer"
      }
    }
  }
}